### ISSUE TITLE
Major issue: Wrong name in install package

### ISSUE THREAD

**Issue by VashJuan** [dnnconsulting/DnnC.Contra#2]
Just joking. Installing this theme shows its implemented on the DNNBooster theme. No biggie, but an easy one to fix.

THANKS for these wonderful themes Geoff!!!

![4-30-2017 at 1 29 35 pm](https://cloud.githubusercontent.com/assets/8594671/25567739/5c89b3b0-2da9-11e7-8f6d-1c592ab31eb8.jpg)

**Comment by dnnconsulting** [comment]
Hi Juan,
Thanks for the heads up, should be fixed now!

Regards,
DnnConsulting.net

**Comment by VashJuan** [comment]
Geoff, as long as I have you: 

 

- For www.dnnmdesign.com <http://www.dnnmdesign.com>   & www.dnnbootster.com <http://www.dnnbootster.com>  -- Any idea why the banner image intermittently shrinks while the slide show does its transition? I saw there was a fix implemented a couple months back that ‘should’ have solved it, but I still see the issue with latest Firefox.

 

- Also any plans to switch DNNContra over to use the (very cool!) new DnnThemeEditor?

 

- Thanks so much for these themes! They are super!

 

- I *might* be willing to help out. Do you have any ideas for simple stuff you’d like to delegate from your priority list? I’ve a long development background, but not much with these current toolsets. I’ve some other priorities too, but would still enjoy trying to help out as I can.

 

- John

 

www.JohnCornelison.org <http://www.JohnCornelison.org>

**Comment by dnnconsulting** [comment]
Hi John,

Try and set the images all the same size, that should solve the problem the easiest way, that's what I do all the time.

The sliders are always a nightmare!

Plans for the DnnThemeEditor on the DnnContra theme, all depends on time. I have started to incorporate the editor on the DnnBooster theme but its not finished yet.

I do have the plan to do so but it's time that's the problem.
As for helping out, any contributions are welcome!
Regards,
Geoff
